import time

import numpy as np
from tqdm import tqdm


def bootstrap_lc(lc, replace=True, rng=None):
    """Generate a bootstrap-resampled light curve.

    Flux values are randomly sampled from the finite flux values of the input
    light curve while preserving the corresponding time sampling and other
    light-curve metadata. The resulting light curve is normalized before
    being returned.

    Parameters
    ----------
    lc : lightkurve.LightCurve
        Light curve whose flux values are to be resampled.
    replace : bool, optional
        If True, sample flux values with replacement. Default is True.
    rng : numpy.random.Generator or None, optional
        Random-number generator used for resampling. If None, a new generator
        is created. Passing a seeded generator allows reproducible results.
        Default is None.

    Returns
    -------
    lightkurve.LightCurve
        Copy of the input light curve with non-finite samples removed and flux
        values resampled and normalized.
    """
    if rng is None:
        rng = np.random.default_rng()

    bootstrapped_lc = lc.copy().remove_nans()
    n_samples = len(bootstrapped_lc)

    bootstrapped_lc.flux = (
        rng.choice(
            bootstrapped_lc.flux.value,
            n_samples,
            replace=replace,
        )
        * bootstrapped_lc.flux.unit
    )

    return bootstrapped_lc.normalize()


def bootstrap_periodogram_samples(
    pw,
    minfreq=None,
    maxfreq=None,
    nruns=100,
    residuals=True,
    statusbar=True,
    timelimit=None,
    rng=None,
    progress_callback=None,
    cancel_check=None,
):
    """Generate bootstrap samples of periodogram peak amplitudes.

    Randomized light curves are generated by resampling the included flux
    values of a `Prewhitener` with replacement. A periodogram is calculated
    for each realization using the frequency grid and periodogram settings
    of the supplied `Prewhitener`.

    For each completed realization, this function records both the maximum
    periodogram amplitude and the median periodogram amplitude. These
    distributions can subsequently be used to estimate a false-alarm
    probability threshold.

    Parameters
    ----------
    pw : Prewhitener
        Analysis object providing the light curve, included-data mask,
        frequency grid, periodogram settings, frequency units, and amplitude
        conversion.
    minfreq : float or None, optional
        Minimum frequency included in the bootstrap periodograms. If None,
        the lower limit is determined by the frequency grid used by `pw`.
        Default is None.
    maxfreq : float or None, optional
        Maximum frequency included in the bootstrap periodograms. If None,
        the upper limit is determined by the frequency grid used by `pw`.
        Default is None.
    nruns : int, optional
        Number of bootstrap realizations to generate. Must be at least 1.
        Default is 100.
    residuals : bool, optional
        If True, generate samples from current residuals time series instead 
        of original data.
        Default is True.
    statusbar : bool, optional
        If True, display a `tqdm` progress bar while generating samples.
        Default is True.
    timelimit : float or None, optional
        Maximum allowed estimated remaining computation time, in seconds.
        If the estimated remaining time exceeds this value, sampling stops
        after the current realization. If None, no time limit is applied.
        Default is None.
    rng : numpy.random.Generator or None, optional
        Random-number generator used for bootstrap resampling. If None, a new
        generator is created. Passing a seeded generator allows reproducible
        results. Default is None.
    progress_callback : callable or None, optional
        Function called after each completed realization as
        ``progress_callback(n_completed, nruns)``.
    cancel_check : callable or None, optional
        Function returning True when the calculation should stop.
        The cancellation state is checked between realizations.

    Returns
    -------
    maxima : numpy.ndarray
        Maximum periodogram amplitude from each completed bootstrap
        realization.
    medians : numpy.ndarray
        Median periodogram amplitude from each completed bootstrap
        realization.

    Notes
    -----
    The ratio `maxima / medians` provides a distribution of peak amplitudes
    relative to the typical periodogram amplitude and can be used to estimate
    a relative significance threshold.

    These brute-force periodogram calculations can take a long time. If
    `timelimit` is not None and the calculation is stopped early, only the
    successfully completed realizations are returned; the arrays are never
    padded with zeros.
    """
    if not isinstance(nruns, (int, np.integer)) or nruns < 1:
        raise ValueError("nruns must be an integer greater than or equal to 1.")
    if timelimit is not None and timelimit <= 0:
        raise ValueError("timelimit must be positive or None.")
    if rng is None:
        rng = np.random.default_rng()

    maxima = []
    medians = []
    recent_durations = []

    # Freeze the selected light curve for this bootstrap run.
    if residuals:
        included_lc = pw.lc_resid[np.where(pw.lc["include"])].copy() + 1.
    else:
        included_lc = pw.lc[np.where(pw.lc["include"])].copy()

    iterator = tqdm(range(nruns)) if statusbar else range(nruns)

    for i in iterator:
        if cancel_check is not None and cancel_check():
            break

        start = time.perf_counter()

        bootstrapped_lc = bootstrap_lc(included_lc, rng=rng)
        per = bootstrapped_lc.to_periodogram(
            minimum_frequency=minfreq,
            maximum_frequency=maxfreq,
            normalization="amplitude",
            freq_unit=pw.freq_unit,
            frequency=pw.freqs,
            ls_method=pw.ls_method,
        ).power.value
        per *= pw.amp_conversion

        medians.append(np.median(per))
        maxima.append(np.max(per))

        if progress_callback is not None:
            progress_callback(i + 1, nruns)

        duration = time.perf_counter() - start
        recent_durations.append(duration)
        recent_durations = recent_durations[-10:]

        if timelimit is not None:
            runs_remaining = nruns - (i + 1)
            estimated_time_left = runs_remaining * np.mean(recent_durations)
            if estimated_time_left > timelimit:
                break

    return np.asarray(maxima), np.asarray(medians)

def bootstrap_threshold_from_samples(
    maxima,
    medians,
    fap=0.01,
    relative=True,
):
    """Calculate a significance threshold from existing bootstrap samples.

    Parameters
    ----------
    maxima : array_like
        Maximum periodogram amplitudes from bootstrap realizations.
    medians : array_like
        Median periodogram amplitudes from the same realizations.
    fap : float, optional
        False-alarm probability. Must satisfy ``0 < fap < 1``.
        Default is 0.01.
    relative : bool, optional
        If True, calculate the threshold from ``maxima / medians``.
        If False, use the absolute maximum amplitudes. Default is True.

    Returns
    -------
    threshold : float
        The ``1 - fap`` quantile of the bootstrap distribution.
    samples : numpy.ndarray
        Samples used to calculate the threshold.
    """
    if not 0 < fap < 1:
        raise ValueError("fap must satisfy 0 < fap < 1.")

    maxima = np.asarray(maxima)
    medians = np.asarray(medians)

    if maxima.ndim != 1 or maxima.size == 0:
        raise ValueError("maxima must be a non-empty one-dimensional array.")

    if medians.shape != maxima.shape:
        raise ValueError("maxima and medians must have the same shape.")

    if relative:
        if np.any(medians == 0):
            raise ZeroDivisionError(
                "At least one bootstrap periodogram has zero median amplitude."
            )
        samples = maxima / medians
    else:
        samples = maxima

    threshold = np.quantile(samples, 1 - fap)

    return threshold, samples

def bootstrap_threshold(
    pw,
    minfreq=None,
    maxfreq=None,
    fap=0.01,
    oversample=10,
    relative=True,
    statusbar=True,
    timelimit=None,
    return_samples=False,
    plot=False,
    log=False,
    rng=None,
):
    """Estimate a periodogram significance threshold by bootstrapping.

    Bootstrap realizations are generated by randomly resampling the included
    flux values of the light curve associated with `pw`. A periodogram is
    calculated for each realization using the frequency grid and periodogram
    settings of `pw`, and the distribution of maximum peak amplitudes is used
    to estimate the requested false-alarm probability threshold.

    When `relative=True`, each maximum amplitude is divided by the median
    periodogram amplitude from the same realization before the threshold is
    calculated. The resulting threshold is therefore expressed relative to
    the characteristic periodogram noise level.

    If sampling is stopped by `timelimit`, no threshold is reported because
    fewer than the requested number of bootstrap realizations were completed.
    The returned dictionary records the completion state and, when requested,
    the successfully completed samples.

    Parameters
    ----------
    pw : Prewhitener
        Analysis object providing the light curve, included-data mask,
        frequency grid, periodogram settings, frequency units, and amplitude
        conversion.
    minfreq : float or None, optional
        Minimum frequency included in the bootstrap periodograms. If None,
        the lower limit is determined by the frequency grid used by `pw`.
        Default is None.
    maxfreq : float or None, optional
        Maximum frequency included in the bootstrap periodograms. If None,
        the upper limit is determined by the frequency grid used by `pw`.
        Default is None.
    fap : float, optional
        False-alarm probability for which to estimate the significance
        threshold. Must satisfy ``0 < fap < 1``. Default is 0.01.
    oversample : float, optional
        Positive factor controlling the number of bootstrap realizations. The
        number of realizations is computed as ``int(oversample / fap)``.
        Default is 10.
    relative : bool, optional
        If True, calculate the threshold from the maximum periodogram
        amplitude divided by the median amplitude of each realization. If
        False, calculate the threshold directly from the maximum amplitudes.
        Default is True.
    statusbar : bool, optional
        If True, display a `tqdm` progress bar while generating bootstrap
        samples. Default is True.
    timelimit : float or None, optional
        Maximum allowed estimated remaining computation time, in seconds.
        If the estimate exceeds this value, sampling stops after the current
        realization and no threshold is reported. If None, no time limit is
        applied. Default is None.
    return_samples : bool, optional
        If True, include the completed bootstrap maximum and median amplitudes
        in the returned dictionary. Default is False.
    plot : bool, optional
        If True, display the bootstrap distribution and cumulative
        distribution function after a complete run. Default is False.
    log : bool, optional
        If True, write start, completion, and timeout messages to the log of
        `pw`. Default is False.
    rng : numpy.random.Generator or None, optional
        Random-number generator used for bootstrap resampling. If None, a new
        generator is created. Passing a seeded generator allows reproducible
        results. Default is None.

    Returns
    -------
    results : dict
        Bootstrap significance-threshold results. The dictionary contains
        ``threshold``, ``FAP``, ``completed``, ``nruns_requested``, and
        ``nruns_completed``. ``threshold`` is None if sampling stops before
        all requested realizations are completed. If `return_samples=True`,
        the dictionary also contains ``medians`` and ``maxima`` arrays for
        the completed realizations.
    """
    if not 0 < fap < 1:
        raise ValueError("fap must satisfy 0 < fap < 1.")
    if oversample <= 0:
        raise ValueError("oversample must be positive.")
    if timelimit is not None and timelimit <= 0:
        raise ValueError("timelimit must be positive or None.")

    nruns = int(oversample / fap)
    if nruns < 1:
        raise ValueError(
            "oversample / fap must correspond to at least one bootstrap run."
        )

    if log:
        logmessage = (
            "Calculating bootstrapped periodogram significance threshold "
            f"for false-alarm probability {fap} using {nruns} noise "
            "realizations. "
        )
        if relative:
            logmessage += "Using peak amplitudes relative to the median noise level. "
        else:
            logmessage += "Using absolute peak amplitudes. "
        logmessage += (
            f"minfreq = {minfreq} and maxfreq = {maxfreq} {pw.freq_unit} "
            "(full range if `None`)."
        )
        pw.log(logmessage)

    maxima, medians = bootstrap_periodogram_samples(
        pw=pw,
        minfreq=minfreq,
        maxfreq=maxfreq,
        nruns=nruns,
        statusbar=statusbar,
        timelimit=timelimit,
        rng=rng,
    )

    nruns_completed = len(maxima)
    completed = nruns_completed == nruns

    results = {
        "threshold": None,
        "FAP": fap,
        "completed": completed,
        "nruns_requested": nruns,
        "nruns_completed": nruns_completed,
    }

    if return_samples:
        results["medians"] = medians
        results["maxima"] = maxima

    if not completed:
        if log:
            pw.log(
                "Bootstrapping stopped because the estimated remaining "
                f"calculation time exceeded {timelimit} seconds "
                f"({nruns_completed}/{nruns} realizations completed).",
                level="warning",
            )
        return results

    if relative:
        if np.any(medians == 0):
            raise ZeroDivisionError(
                "At least one bootstrap periodogram has zero median amplitude; "
                "a relative threshold cannot be calculated."
            )
        samples = maxima / medians
    else:
        samples = maxima

    threshold,_ = bootstrap_threshold_from_samples(maxima, medians,
                                                 fap=fap, relative=relative)
    results["threshold"] = threshold

    if plot:
        plot_bootstrap(samples, fap=fap)

    if log:
        mode = "relative" if relative else "absolute"
        pw.log(
            f"Bootstrap {mode} significance threshold = {threshold:.6g} "
            f"for false-alarm probability {fap}."
        )

    return results


def plot_bootstrap(samples, fap=0.05, ax=None):
    """Plot a bootstrap distribution and its cumulative distribution.

    The bootstrap samples are displayed as a histogram, with their empirical
    cumulative distribution function shown on a secondary y-axis. The
    quantile corresponding to the requested false-alarm probability is
    indicated by a vertical line.

    Parameters
    ----------
    samples : array_like
        Bootstrap samples from which to construct the histogram and empirical
        cumulative distribution function.
    fap : float, optional
        False-alarm probability used to determine the plotted threshold. The
        threshold is the ``1 - fap`` quantile of `samples`. Must satisfy
        ``0 < fap < 1``. Default is 0.05.
    ax : matplotlib.axes.Axes or None, optional
        Axes on which to draw the histogram. If None, a new figure and axes
        are created and shown. Default is None.

    Returns
    -------
    ax : matplotlib.axes.Axes
        Axes containing the bootstrap-sample histogram.
    ax_cdf : matplotlib.axes.Axes
        Secondary axes containing the empirical cumulative distribution
        function.
    """
    import matplotlib.pyplot as plt

    if not 0 < fap < 1:
        raise ValueError("fap must satisfy 0 < fap < 1.")

    samples = np.asarray(samples)
    if samples.ndim != 1 or samples.size == 0:
        raise ValueError("samples must be a non-empty one-dimensional array.")
    if not np.all(np.isfinite(samples)):
        raise ValueError("samples must contain only finite values.")

    created_ax = ax is None
    if created_ax:
        _, ax = plt.subplots(figsize=(5, 3))

    ax.hist(samples, bins="auto", alpha=0.7)
    ax.set_xlabel("highest peak")
    ax.set_ylabel("count")

    ax_cdf = ax.twinx()
    xs = np.sort(samples)
    cdf = np.arange(1, len(xs) + 1) / len(xs)

    cdf_color = "darkolivegreen"
    ax_cdf.plot(xs, cdf, color=cdf_color, lw=2)
    ax_cdf.set_ylabel("Cumulative Density Function", color=cdf_color)
    ax_cdf.tick_params(axis="y", colors=cdf_color)
    ax_cdf.spines["right"].set_color(cdf_color)
    ax_cdf.set_ylim(0, 1)

    threshold = np.quantile(samples, 1 - fap)
    ax.axvline(threshold, ls="--", c="k")
    text_offset = np.ptp(samples)*0.02
    ax.text(
        threshold + text_offset,
        0.5,
        f"FAP = {fap}",
        rotation=90,
        transform=ax.get_xaxis_transform(),
        va="center",
        ha="left",
    )

    ax.figure.tight_layout()
    if created_ax:
        plt.show()

    return ax, ax_cdf
